// __tests__/RootLayout.test.js
import React from "react";
import { render, screen } from "@testing-library/react";
import RootLayout, { metadata } from "../app/layout"; // adjust path if needed

// Mock next/font/google to avoid errors
jest.mock("next/font/google", () => ({
  Geist: jest.fn(() => ({ variable: "geist-sans-class" })),
  Geist_Mono: jest.fn(() => ({ variable: "geist-mono-class" })),
}));

describe("RootLayout component", () => {
  beforeEach(() => {
    // Clean up document.body and document.documentElement between tests
    document.body.innerHTML = "";
    document.documentElement.innerHTML = "";
  });

  test("renders children inside body", () => {
    render(
      <RootLayout>
        <div data-testid="child">Hello World</div>
      </RootLayout>
    );

    const child = screen.getByTestId("child");
    expect(child).toBeInTheDocument();
    expect(child).toHaveTextContent("Hello World");
  });

  test("applies font classes to body", () => {
    render(
      <RootLayout>
        <div>Test</div>
      </RootLayout>
    );

    const body = document.querySelector("body");
    expect(body).toHaveClass("geist-sans-class");
    expect(body).toHaveClass("geist-mono-class");
    expect(body).toHaveClass("antialiased");
  });

  test("renders html element with lang attribute", () => {
    render(
      <RootLayout>
        <div>Test</div>
      </RootLayout>
    );

    const html = document.querySelector("html");
    expect(html).toHaveAttribute("lang", "en");
  });

  // ---- Metadata coverage ----
  test("metadata object has expected properties", () => {
    expect(metadata).toHaveProperty("title", "Globe Talk");
    expect(metadata).toHaveProperty("description", "Generated by create next app");
    expect(metadata.icons).toHaveProperty("icon", "/images/LogoVPP-1.png");
  });
});
