// __tests__/RootLayout.test.js
import React from "react";
import ReactDOMServer from "react-dom/server";
import RootLayout, { metadata } from "../app/layout"; // adjust path if needed

// Mock next/font/google to avoid errors
jest.mock("next/font/google", () => ({
  Geist: jest.fn(() => ({ variable: "geist-sans-class" })),
  Geist_Mono: jest.fn(() => ({ variable: "geist-mono-class" })),
}));

describe("RootLayout component", () => {
  test("renders children inside body", () => {
    const markup = ReactDOMServer.renderToStaticMarkup(
      <RootLayout>
        <div data-testid="child">Hello World</div>
      </RootLayout>
    );
    expect(markup).toContain("Hello World");
    expect(markup).toMatch(/<body[\s\S]*?>[\s\S]*Hello World[\s\S]*<\/body>/);
  });

  test("applies font classes to body", () => {
    const markup = ReactDOMServer.renderToStaticMarkup(
      <RootLayout>
        <div>Test</div>
      </RootLayout>
    );
    expect(markup).toContain("antialiased");
  });

  test("renders html element with lang attribute", () => {
    const markup = ReactDOMServer.renderToStaticMarkup(
      <RootLayout>
        <div>Test</div>
      </RootLayout>
    );
    expect(markup).toMatch(/<html[^>]*lang=\"en\"/);
  });

  // ---- Metadata coverage ----
  test("metadata object has expected properties", () => {
    expect(metadata).toHaveProperty("title", "Globe Talk");
    expect(metadata).toHaveProperty("description", "Generated by create next app");
    expect(metadata.icons).toHaveProperty("icon", "/images/LogoVPP-1.png");
  });
});
