// export const quiz = {
//   totalQuestions: 15,
//   questions: [
//     {
//       id: 1,
//       question: 'What is the capital of Japan?',
//       answers: ['Seoul', 'Beijing', 'Tokyo', 'Bangkok'],
//       correctAnswer: 'Tokyo',
//     },
//     {
//       id: 2,
//       question: 'Which country has the largest population in the world?',
//       answers: ['India', 'United States', 'China', 'Indonesia'],
//       correctAnswer: 'China',
//     },
//     {
//       id: 3,
//       question: 'What is the smallest country in the world by land area?',
//       answers: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
//       correctAnswer: 'Vatican City',
//     },
//     {
//       id: 4,
//       question: 'Which country is known as the Land of the Rising Sun?',
//       answers: ['China', 'Thailand', 'Japan', 'South Korea'],
//       correctAnswer: 'Japan',
//     },
//     {
//       id: 5,
//       question: 'What is the official language of Brazil?',
//       answers: ['Spanish', 'Portuguese', 'French', 'English'],
//       correctAnswer: 'Portuguese',
//     },
//     {
//       id: 6,
//       question: 'Which country is home to the kangaroo?',
//       answers: ['South Africa', 'New Zealand', 'Argentina', 'Australia'],
//       correctAnswer: 'Australia',
//     },
//     {
//       id: 7,
//       question: 'What is the capital of Canada?',
//       answers: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'],
//       correctAnswer: 'Ottawa',
//     },
//     {
//       id: 8,
//       question: 'Which country has the most natural lakes?',
//       answers: ['United States', 'Russia', 'Canada', 'China'],
//       correctAnswer: 'Canada',
//     },
//     {
//       id: 9,
//       question: 'What is the largest country by land area?',
//       answers: ['China', 'United States', 'Russia', 'Canada'],
//       correctAnswer: 'Russia',
//     },
//     {
//       id: 10,
//       question: 'Which European country is shaped like a boot?',
//       answers: ['Greece', 'Italy', 'Spain', 'Portugal'],
//       correctAnswer: 'Italy',
//     },
//     {
//       id: 11,
//       question: 'What is the capital of Egypt?',
//       answers: ['Alexandria', 'Cairo', 'Luxor', 'Giza'],
//       correctAnswer: 'Cairo',
//     },
//     {
//       id: 12,
//       question: 'Which country is known as the Land of the Midnight Sun?',
//       answers: ['Sweden', 'Finland', 'Norway', 'Iceland'],
//       correctAnswer: 'Norway',
//     },
//     {
//       id: 13,
//       question: 'What is the official language of Argentina?',
//       answers: ['Portuguese', 'Spanish', 'Italian', 'French'],
//       correctAnswer: 'Spanish',
//     },
//     {
//       id: 14,
//       question: 'Which country has the most islands?',
//       answers: ['Philippines', 'Indonesia', 'Sweden', 'Greece'],
//       correctAnswer: 'Sweden',
//     },
//     {
//       id: 15,
//       question: 'What is the capital of South Africa?',
//       answers: ['Johannesburg', 'Cape Town', 'Pretoria', 'Durban'],
//       correctAnswer: 'Pretoria',
//     },
//   ],
// };