name: Run Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Clean npm cache (optional)
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install --include=dev

    - name: Fix permissions (optional but helpful on Linux)
      run: chmod +x ./node_modules/.bin/*

    - name: Run tests with coverage
      run: npm test -- --coverage --no-cache || true
 

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        fail_ci_if_error: true
